version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - '27017:27017'
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    container_name: server_container
    ports:
      - '5002:5002'
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/mern-stack-app-db
