version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongo_server
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - my_network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server_container
    ports:
      - "5001:5001"
    environment:
      - MONGO_URL=mongodb://mongo_server:27017/mern-stack-app-db
    depends_on:
      - mongodb
    networks:
      - my_network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client_container
    ports:
      - "3000:3000"
    depends_on:
      - server
    networks:
      - my_network

volumes:
  mongo_data:

networks:
  my_network:
