version: '3.8'

services:
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    container_name: server_container_1
    ports:
      - "5001:5001"
    depends_on:
      - mongodb
  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
    container_name: client_container_1
    ports:
      - "3000:3000"
    depends_on:
      - server
  mongodb:
    image: mongo:latest
    container_name: mongo_server
    ports:
      - "27018:27018"
    volumes:
      - ./../mydata:/data/db
volumes:
  mydata: